config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users do
    get :admin, on: :collection
  end
  
  resources :classifieds do
    get 'inquiry', to: 'inquiry#classified_index'
    post 'inquiry/confirm', to: 'inquiry#classified_confirm'
    post 'inquiry/thanks', to: 'inquiry#classified_thanks'
  end
  resources :areas, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :items, only: [:show]
  
  get 'inquiry', to: 'inquiry#index'
  post 'inquiry/confirm', to: 'inquiry#confirm'
  post 'inquiry/thanks', to: 'inquiry#thanks'
  
  get 'policy', to: 'classifieds#policy'
  get 'term', to: 'classifieds#term'
  get 'sitemap', to: redirect('https://s3-ap-northeast-1.amazonaws.com/calgary-board/sitemaps/sitemap.xml.gz')

end

app/models/classified.rb
class Classified < ApplicationRecord
  belongs_to :user
  belongs_to :area
  belongs_to :category
  mount_uploader :image_1, ImageUploader
  mount_uploader :image_2, ImageUploader
  mount_uploader :image_3, ImageUploader
  mount_uploader :image_4, ImageUploader

  validates :user_id, presence: true
  validates :area_id, presence: true
  validates :category_id, presence: true
  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :tel, length: { maximum: 20 }
  
  validate :image_presence
  validates_acceptance_of :agreement, allow_nil: false, on: :create
  
  def image_presence
    if image_2.present? && image_1.blank?
      errors.add(:image_2, "写真は1から順に入れてください")
      elsif image_3.present? && image_1.blank?
        errors.add(:image_3, "写真は1から順に入れてください")
      elsif image_4.present? && image_1.blank?
        errors.add(:image_4, "写真は1から順に入れてください")
    end
  end
end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
  before_action :require_user_logged_in, only: [:create, :edit, :destroy]
  before_action :set_classified, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:destroy, :edit]

  def index
    @classfied = Classified.order(updated_at: :desc).page(params[:page]).per(10)
    @new_classifieds = Classified.order(created_at: :desc).page(params[:page]).per(10)
  end
  
  def new
    @classified = Classified.new
  end

  def create
    @classified = current_user.classifieds.build(classified_params)
    if @classified.save
      flash[:green] = '投稿されました'
      redirect_to classifieds_url
    else
      flash.now[:red] = '投稿されませんでした'
      render :new
    end
  end

  def destroy
    @classified = Classified.find(params[:id])
    @classified.destroy
    
    flash[:green] = '投稿は削除されました'
    redirect_to classifieds_url
    
  end

  def show
  end

  def edit
  end
  
  private
  
  def set_classified
    @classified = Classified.find(params[:id])
  end
  
  def correct_user
    @classified = current_user.classifieds.find_by(id: params[:id])
    unless @classified
      redirect_to root_url  unless current_user.admin_flag?
    end
  end
  
  def classified_params
    params.require(:classified).permit(
      :title,
      :content,
      :category_id,
      :item_id,
      :area_id,
      :tel,
      :user,
      :image_1,
      :image_1_cache,
      :image_2,
      :image_2_cache,
      :image_3,
      :image_3_cache,
      :image_4,
      :image_4_cache,
      :agreement
      )
  end
end

app/views/classifieds/_form.html.erb
<div class="text-center flow-text">
  <h2 class="center-align">クラシファイド投稿</h2>
</div>

  <%= form_for(@classified) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
    
    <div class="input-field col s12">
      <%= f.label :title, 'タイトル' %>
      <%= f.text_field :title, autocomplete: true %>
    </div>
    <div class="input-field col s6 m6">
      <%= f.collection_select :area_id, Area.all, :id, :name, prompt: "エリア" %>
    </div>
    <div class="input-field col s6 m6">
      <%= f.collection_select :category_id, Category.all, :id, :name, prompt: "カテゴリー" %>
    </div>
    <div class="file-field input-field col s12">
      <div class="btn">
        <span>File</span>
        <input type="file">
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text" placeholder="1つ目の写真を選択">
      </div> 
        <%= f.file_field :image_1 %>
    </div>
    
    <div class="file-field input-field col s12">
      <div class="btn">
        <span>File</span>
        <input type="file">
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text" placeholder="２つ目の写真を選択">
      </div> 
        <%= f.file_field :image_2 %>
    </div>
    
    <div class="file-field input-field col s12">
      <div class="btn">
        <span>File</span>
        <input type="file">
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text" placeholder="3つ目の写真を選択">
      </div> 
        <%= f.file_field :image_3 %>
    </div>
    
    <div class="file-field input-field col s12">
      <div class="btn">
        <span>File</span>
        <input type="file">
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text" placeholder="4つ目の写真を選択">
      </div> 
        <%= f.file_field :image_4 %>
    </div>
    <div class="input-field col s12">
      <%= f.label :content, '本文', class: 'active' %>
      <%= f.text_area :content, autocomplete: true, class: "materialize-textarea" %>
    </div>
    <div class="input-field col s12">
      <label>
        <%= f.check_box :agreement, :as => :boolean, checked:false %>
        <span><%= link_to "利用規約", term_path %>と<%= link_to "プライバシーポリシー", policy_path %>に同意する</span>
      </label>
      <br>
      <br>
    </div>
    <div class="input-field col s12">
      <%= f.submit '投稿', class: 'grey-text text-lighten-3 waves-effect waves-light btn red' %>
    </div>
    
  <% end %>

app/views/classifieds/create.html.erb
<h1>Classifieds#create</h1>
<p>Find me in app/views/classifieds/create.html.erb</p>

app/views/classifieds/destroy.html.erb
<h1>Classifieds#destroy</h1>
<p>Find me in app/views/classifieds/destroy.html.erb</p>

app/views/classifieds/edit.html.erb
<h1>Classifieds#edit</h1>
<p>Find me in app/views/classifieds/edit.html.erb</p>

app/views/classifieds/index.html.erb
<div class="col s12 m9 push-m3">
  <div class="fixed-action-btn">
    <%= link_to '<i class="large material-icons">mode_edit</i>'.html_safe, new_classified_path, class: "btn-floating btn-large waves-effect waves-light red" %>
  </div>
  <% breadcrumb :classifieds %>
  <% @new_classifieds.each do |classified| %>
    <div class="card">
      <div class="card-content">
        <span class="card-title"><%= classified.title.truncate(50) %></span>
        <p><span class="badge"><%= classified.updated_at %></span></p>
      </div>
      <div class="card-action">
        <%= link_to '詳細'.html_safe, classified %><span class="new badge red" data-badge-caption=""><%= classified.category.name %></span><span class="new badge blue" data-badge-caption=""><%= classified.area.name %></span>
      </div>
    </div>
  <% end %>
  <div class="col s12 m9 center-align">
    <%= paginate @new_classifieds %>
  </div>
</div>
<div class="col s12 m3 pull-m9">
  <%= render 'layouts/sidebar' %>
</div>

app/views/classifieds/new.html.erb
<%= render 'form', classfied: @classified %>

app/views/classifieds/policy.html.erb
<div class="col s12">
  <h4>プライバシーポリシー</h4>
  <p>Cloud calgary（以下，「当社」といいます。）は，本ウェブサイト上で提供するサービス（以下,「本サービス」といいます。）におけるプライバシー情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。</p>
  
  <h4>第1条（プライバシー情報）</h4>
  <ul>
    <li>プライバシー情報のうち「個人情報」とは，個人情報保護法にいう「個人情報」を指すものとし，生存する個人に関する情報であって，当該情報に含まれる氏名，生年月日，住所，電話番号，連絡先その他の記述等により特定の個人を識別できる情報を指します。</li>
    <li>プライバシー情報のうち「履歴情報および特性情報」とは，上記に定める「個人情報」以外のものをいい，ご利用いただいたサービスやご購入いただいた商品，ご覧になったページや広告の履歴，ユーザーが検索された検索キーワード，ご利用日時，ご利用の方法，ご利用環境，郵便番号や性別，職業，年齢，ユーザーのIPアドレス，クッキー情報，位置情報，端末の個体識別情報などを指します。</li>
  </ul>
  
  <h4>第２条（プライバシー情報の収集方法）</h4>
  <ul>
    <li>当社は，ユーザーが利用登録をする際に氏名，電話番号，メールアドレスなどの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や，決済に関する情報を当社の提携先（情報提供元，広告主，広告配信先などを含みます。以下，｢提携先｣といいます。）などから収集することがあります。</li>
    <li>当社は，ユーザーについて，利用したサービスや，閲覧したページや広告の履歴，検索した検索キーワード，利用日時，利用方法，利用環境（携帯端末を通じてご利用の場合の当該端末の通信状態，利用に際しての各種設定情報なども含みます），IPアドレス，クッキー情報，位置情報，端末の個体識別情報などの履歴情報および特性情報を，ユーザーが当社や提携先のサービスを利用しまたはページを閲覧する際に収集します。</li>
  </ul>
  
  <h4>第３条（個人情報を収集・利用する目的）</h4>
  <p>当社が個人情報を収集・利用する目的は，以下のとおりです。</p>
  <ul>
    <li>（1）ユーザーに自分の登録情報の閲覧や修正，利用状況の閲覧を行っていただくために，氏名，住所，連絡先，支払方法などの登録情報，利用されたサービスや購入された商品，およびそれらの代金などに関する情報を表示する目的</li>
    <li>（2）ユーザーにお知らせや連絡をするためにメールアドレスを利用する場合やユーザーに商品を送付したり必要に応じて連絡したりするため，氏名や住所などの連絡先情報を利用する目的</li>
    <li>（3）ユーザーに代金を請求するために，購入された商品名や数量，利用されたサービスの種類や期間，回数，請求金額，氏名，住所，銀行口座番号やクレジットカード番号などの支払に関する情報などを利用する目的</li>
    <li>（4）ユーザーが簡便にデータを入力できるようにするために，当社に登録されている情報を入力画面に表示させたり，ユーザーのご指示に基づいて他のサービスなど（提携先が提供するものも含みます）に転送したりする目的</li>
    <li>（5）代金の支払を遅滞したり第三者に損害を発生させたりするなど，本サービスの利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの利用をお断りするために，利用態様，氏名や住所など個人を特定するための情報を利用する目的</li>
    <li>（6）ユーザーからのお問い合わせに対応するために，お問い合わせ内容や代金の請求に関する情報など当社がユーザーに対してサービスを提供するにあたって必要となる情報や，ユーザーのサービス利用状況，連絡先情報などを利用する目的</li>
    <li>（7）上記の利用目的に付随する目的</li>
  </ul>
  
  <h4>第４条（個人情報の第三者提供）</h4>
  <br>
    <p>当社は，次に掲げる場合を除いて，あらかじめユーザーの同意を得ることなく，第三者に個人情報を提供することはありません。ただし，個人情報保護法その他の法令で認められる場合を除きます。</p>
    
  <ul>
    <li>（1）法令に基づく場合</li>
    <li>（2）人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき</li>
    <li>（3）公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき</li>
    <li>（4）国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき</li>
    <li>（5）予め次の事項を告知あるいは公表をしている場合</li>
  </ul>
  <ol>
    <li>利用目的に第三者への提供を含むこと</li>
    <li>第三者に提供されるデータの項目</li>
    <li>第三者への提供の手段または方法</li>
    <li>本人の求めに応じて個人情報の第三者への提供を停止すること</li>
  </ol>
  <p>前項の定めにかかわらず，次に掲げる場合は第三者には該当しないものとします。</p>
  <ul>
    <li>（1）当社が利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合</li>
    <li>（2）合併その他の事由による事業の承継に伴って個人情報が提供される場合</li>
    <li>（3）個人情報を特定の者との間で共同して利用する場合であって，その旨並びに共同して利用される個人情報の項目，共同して利用する者の範囲，利用する者の利用目的および当該個人情報の管理について責任を有する者の氏名または名称について，あらかじめ本人に通知し，または本人が容易に知り得る状態に置いているとき</li>
  </ul>
  
  <h4>第５条（個人情報の訂正および削除）</h4>
  <ul>
    <li>ユーザーは，当社の保有する自己の個人情報が誤った情報である場合には，当社が定める手続きにより，当社に対して個人情報の訂正または削除を請求することができます。</li>
    <li>当社は，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正または削除を行い，これをユーザーに通知します。</li>
  </ul>
  
  <h4>第６条（個人情報の利用停止等）</h4>
  <p>当社は，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行い，その結果に基づき，個人情報の利用停止等を行い，その旨本人に通知します。ただし，個人情報の利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，本人の権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じます。</p>
  
  <h4>第７条（プライバシーポリシーの変更）</h4>
  <ul>
    <li>本ポリシーの内容は，ユーザーに通知することなく，変更することができるものとします。</li>
    <li>当社が別途定める場合を除いて，変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。</li>
  </ul>
  
  <h4>第８条（お問い合わせ窓口）</h4>
  <p>本ポリシーに関するお問い合わせは，下記の窓口までお願いいたします。</p>
  <p>CJ cloud</p>
  <p>Eメールアドレス：info@cloud-calgary.com</p>
  
  <p class="right">以上</p>
</div>

app/views/classifieds/show.html.erb
<div class="col s12 m9 push-m3">
   <% breadcrumb :detail %>
  <div class="card">
    <div class="card-content">
      <span class="card-title"><%= @classified.title %></span>
      <div class="card-image">
        <% if @classified.image_1? %>
        <div class="slider">
          <ul class="slides">
            <li>
              <%= image_tag @classified.image_1.url.to_s, class: "materialboxed" %>
            </li>
            <% if @classified.image_2? %>
            <li>
              <%= image_tag @classified.image_2.url.to_s, class: "materialboxed" %>
            </li>
            <% end %>
            <% if @classified.image_3? %>
            <li>
              <%= image_tag @classified.image_3.url.to_s, class: "materialboxed" %>
            </li>
            <% end %>
            <% if @classified.image_4? %>
            <li>
              <%= image_tag @classified.image_4.url.to_s, class: "materialboxed" %>
            </li>
            <% end %>
          </ul>
          
        </div>
        <% end %>
        <p><span class="badge">更新日：<%= @classified.updated_at %></span><span class="new badge red" data-badge-caption=""><%= @classified.category.name %></span><span class="new badge blue" data-badge-caption=""><%= @classified.area.name %></span></p>
        
        <p class="post_content">
          内容：<br><br>
          <%= @classified.content %>
        </p>
        <div class="card_content">
          投稿者：<%= @classified.user.name %>
        </div>
      </div>
    </div>
    <div class="card-action">
      <%= link_to '<i class="material-icons right">send</i>メール'.html_safe, classified_inquiry_path(@classified), class: "waves-effect waves-light btn" %>
      <% if current_user == @classified.user %>
        <%= link_to '編集', edit_classified_path(@classified), class: "waves-effect waves-light btn current_user_btn blue" %>
        <%= link_to '削除', @classified, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: "waves-effect waves-light btn current_user_btn red" %>
      <% end %>
    </div>
  </div>
</div>
<div class="col s12 m3 pull-m9">
  <%= render 'layouts/sidebar' %>
</div>

app/views/classifieds/term.html.erb
<div class="col s12">
  <h3>利用規約</h3>
  
  <p>この利用規約（以下，「本規約」といいます。）は，Cloud Calgary（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。</p>
  <br>
  <h4>第1条（適用）</h4>
  <br>
  <p>本規約は，ユーザーと当社との間の本サービスの利用に関わる一切の関係に適用されるものとします。</p>
  <br>
  <h4>第2条（利用登録）</h4>
  <br>
  <p>登録希望者が当社の定める方法によって利用登録を申請し，当社がこれを承認することによって，利用登録が完了するものとします。</p>
  <p>当社は，利用登録の申請者に以下の事由があると判断した場合，利用登録の申請を承認しないことがあり，その理由については一切の開示義務を負わないものとします。</p>
  <ul>
    <li>（1）利用登録の申請に際して虚偽の事項を届け出た場合</li>
    <li>（2）本規約に違反したことがある者からの申請である場合</li>
    <li>（3）未成年者，成年被後見人，被保佐人または被補助人のいずれかであり，法定代理人，後見人，保佐人または補助人の同意等を得ていなかった場合</li>
    <li>（4）反社会的勢力等（暴力団，暴力団員，右翼団体，反社会的勢力，その他これに準ずる者を意味します。）である，または資金提供その他を通じて反社会的勢力等の維持，運営もしくは経営に協力もしくは関与する等反社会的勢力との何らかの交流もしくは関与を行っていると当社が判断した場合</li>
    <li>（5）その他，当社が利用登録を相当でないと判断した場合</li>
  </ul>
  <br>
  <h4>第3条（ユーザーIDおよびパスワードの管理）</h4>
  <br>
  <p>ユーザーは，自己の責任において，本サービスのユーザーIDおよびパスワードを管理するものとします。<br>
  ユーザーは，いかなる場合にも，ユーザーIDおよびパスワードを第三者に譲渡または貸与することはできません。当社は，ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には，そのユーザーIDを登録しているユーザー自身による利用とみなします。</p>
  <h4>第4条（禁止事項）</h4>
  <br>
  <p>ユーザーは，本サービスの利用にあたり，以下の行為をしてはなりません。</p>
  <ul>
    <li>（1）法令または公序良俗に違反する行為</li>
    <li>（2）犯罪行為に関連する行為</li>
    <li>（3）当社のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為</li>
    <li>（4）当社のサービスの運営を妨害するおそれのある行為</li>
    <li>（5）他のユーザーに関する個人情報等を収集または蓄積する行為</li>
    <li>（6）他のユーザーに成りすます行為</li>
    <li>（7）当社のサービスに関連して，反社会的勢力に対して直接または間接に利益を供与する行為</li>
    <li>（8）当社，本サービスの他の利用者または第三者の知的財産権，肖像権，プライバシー，名誉その他の権利または利益を侵害する行為</li>
    <li>（9）過度に暴力的な表現，露骨な性的表現，人種，国籍，信条，性別，社会的身分，門地等による差別につながる表現，自殺，自傷行為，薬物乱用を誘引または助長する表現，その他反社会的な内容を含み他人に不快感を与える表現を，投稿または送信する行為</li>
    <li>（10）営業，宣伝，広告，勧誘，その他営利を目的とする行為（当社の認めたものを除きます。），性行為やわいせつな行為を目的とする行為，面識のない異性との出会いや交際を目的とする行為，他のお客様に対する嫌がらせや誹謗中傷を目的とする行為，その他本サービスが予定している利用目的と異なる目的で本サービスを利用する行為</li>
    <li>（11）宗教活動または宗教団体への勧誘行為</li>
    <li>（12）その他，当社が不適切と判断する行為</li>
  </ul>
  <br>
  <h4>第5条（本サービスの提供の停止等）</h4>
  <br>
  <p>当社は，以下のいずれかの事由があると判断した場合，ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。</p>
  <ul>
    <li>（1）本サービスにかかるコンピュータシステムの保守点検または更新を行う場合</li>
    <li>（2）地震，落雷，火災，停電または天災などの不可抗力により，本サービスの提供が困難となった場合</li>
    <li>（3）コンピュータまたは通信回線等が事故により停止した場合</li>
    <li>（4）その他，当社が本サービスの提供が困難と判断した場合</li>
  </ul>
  <p>当社は，本サービスの提供の停止または中断により，ユーザーまたは第三者が被ったいかなる不利益または損害について，理由を問わず一切の責任を負わないものとします。</p>
  <h4>第6条（著作権）</h4>
  <br>
  <p>ユーザーは，自ら著作権等の必要な知的財産権を有するか，または必要な権利者の許諾を得た文章，画像や映像等の情報のみ，本サービスを利用し，投稿または編集することができるものとします。<br>
  ユーザーが本サービスを利用して投稿または編集した文章，画像，映像等の著作権については，当該ユーザーその他既存の権利者に留保されるものとします。ただし，当社は，本サービスを利用して投稿または編集された文章，画像，映像等を利用できるものとし，ユーザーは，この利用に関して，著作者人格権を行使しないものとします。<br>
  前項本文の定めるものを除き，本サービスおよび本サービスに関連する一切の情報についての著作権およびその他知的財産権はすべて当社または当社にその利用を許諾した権利者に帰属し，ユーザーは無断で複製，譲渡，貸与，翻訳，改変，転載，公衆送信（送信可能化を含みます。），伝送，配布，出版，営業使用等をしてはならないものとします。</p>
  <h4>第7条（利用制限および登録抹消）</h4>
  <br>
  <p>当社は，以下の場合には，事前の通知なく，投稿データを削除し，ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。</p>
  <ul>
    <li>（1）本規約のいずれかの条項に違反した場合</li>
    <li>（2）登録事項に虚偽の事実があることが判明した場合</li>
    <li>（3）破産，民事再生，会社更生または特別清算の手続開始決定等の申立がなされたとき</li>
    <li>（4）1年間以上本サービスの利用がない場合</li>
    <li>（5）当社からの問い合わせその他の回答を求める連絡に対して30日間以上応答がない場合</li>
    <li>（6）第2条第2項各号に該当する場合</li>
    <li>（7）その他，当社が本サービスの利用を適当でないと判断した場合</li>
  </ul>
  <p>前項各号のいずれかに該当した場合，ユーザーは，当然に当社に対する一切の債務について期限の利益を失い，その時点において負担する一切の債務を直ちに一括して弁済しなければなりません。<br>
  当社は，本条に基づき当社が行った行為によりユーザーに生じた損害について，一切の責任を負いません。</p>
  <h4>第8条（保証の否認および免責事項）</h4>
  <br>
  <p>当社は，本サービスに事実上または法律上の瑕疵（安全性，信頼性，正確性，完全性，有効性，特定の目的への適合性，セキュリティなどに関する欠陥，エラーやバグ，権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。<br>
  当社は，本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし，本サービスに関する当社とユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合，この免責規定は適用されません。<br>
  前項ただし書に定める場合であっても，当社は，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害のうち特別な事情から生じた損害（当社またはユーザーが損害発生につき予見し，または予見し得た場合を含みます。）について一切の責任を負いません。また，当社の過失（重過失を除きます。）による債務不履行または不法行為によりユーザーに生じた損害の賠償は，ユーザーから当該損害が発生した月に受領した利用料の額を上限とします。<br>
  当社は，本サービスに関して，ユーザーと他のユーザーまたは第三者との間において生じた取引，連絡または紛争等について一切責任を負いません。</p>
  <h4>第9条（サービス内容の変更等）</h4>
  <br>
  <p>当社は，ユーザーに通知することなく，本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし，これによってユーザーに生じた損害について一切の責任を負いません。</p>
  <br>
  <h4>第10条（利用規約の変更）</h4>
  <br>
  <p>当社は，必要と判断した場合には，ユーザーに通知することなくいつでも本規約を変更することができるものとします。</p>
  
  <h4>第11条（通知または連絡）</h4>
  
  <p>ユーザーと当社との間の通知または連絡は，当社の定める方法によって行うものとします。</p>
  <p>連絡先：info@cloud-calgary.com</p>
  <h4>第12条（権利義務の譲渡の禁止）</h4>
  
  <p>ユーザーは，当社の書面による事前の承諾なく，利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し，または担保に供することはできません。</p>
  
  <h4>第13条（個人情報の保護）</h4>
  <p>当サイトが別途定める<%= link_to "プライバシーポリシー", policy_path %>を遵守します。</p>
</div>