config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users do
    get :admin, on: :collection
  end
  
  resources :classifieds do
    get 'inquiry', to: 'inquiry#classified_index'
    post 'inquiry/confirm', to: 'inquiry#classified_confirm'
    post 'inquiry/thanks', to: 'inquiry#classified_thanks'
  end
  resources :areas, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :items, only: [:show]
  
  get 'inquiry', to: 'inquiry#index'
  post 'inquiry/confirm', to: 'inquiry#confirm'
  post 'inquiry/thanks', to: 'inquiry#thanks'
  
  get 'policy', to: 'classifieds#policy'
  get 'term', to: 'classifieds#term'
  get 'sitemap', to: redirect('https://s3-ap-northeast-1.amazonaws.com/calgary-board/sitemaps/sitemap.xml.gz')

end

app/models/inquiry.rb
class Inquiry
  include ActiveModel::Model
 
  attr_accessor :name, :email, :message
 
  validates :name, :presence => {:message => '名前を入力してください'}
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
  validates :message, :presence => {:message => 'メッセージをを入力してください'}
end

app/controllers/inquiry_controller.rb
class InquiryController < ApplicationController
  def index
    @inquiry = Inquiry.new
    render :action => 'index'
  end

  def confirm
    @inquiry = Inquiry.new(params_inquiry)
    if @inquiry.valid?
      render :action => 'confirm'
    else
      render :action => 'index'
    end
  end

  def thanks
    @inquiry = Inquiry.new(params_inquiry)
    NoticeMailer.send_mail(@inquiry).deliver

    render :action => 'thanks'
  end
  
  def classified_index
    @classified = Classified.find(params[:classified_id])
    @inquiry = Inquiry.new
  end
  
  def classified_confirm
    @classified = Classified.find(params[:classified_id])
    @inquiry = Inquiry.new(params_inquiry)
    if @inquiry.valid?
      render :action => 'classified_confirm'
    else
      render :action => 'classified_index'
    end
  end

  def classified_thanks
    @classified = Classified.find(params[:classified_id])
    @user = @classified.user
    @inquiry = Inquiry.new(params_inquiry)
    NoticeMailer.send_mail(@inquiry, @user).deliver
    render :action => 'classified_thanks'
  end

  private
  def params_inquiry
    params.require(:inquiry).permit(:name, :email, :message, :user)
  end
end

app/views/inquiry/classified_confirm.html.erb
<div class="jumbotron back-jumbo">
<div class="page-header">
  <h2>確認画面</h2>
</div>
 
<%= form_for @inquiry, :url => classified_inquiry_thanks_path(@classified) do |f| %>
  <table class="table">
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :name %>
        <%= @inquiry.name %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @inquiry.email %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@inquiry.message) %>
      </td>
    </tr>
  </table>
  <%= f.submit '送信', :class => 'waves-effect waves-light btn white-text' %>
<% end %>
</div>

app/views/inquiry/classified_index.html.erb
<div class="col s12">
  <% breadcrumb :inquiry %>
  <h2>お問い合わせフォーム</h2>
  <%= form_for @inquiry, :url => classified_inquiry_confirm_path(@classified) do |f| %>
    <% if @inquiry.errors.any? %>
      <div class="error">
        <strong>入力内容にエラーがあります</strong>
        <ul>
          <% @inquiry.errors.each do |attr, msg| %>
            <li>
              <script type="text/javascript">
              M.toast({html: '<%= msg %>', classes: 'rounded #0288d1 light-blue darken-2'})
              </script>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="input-field col s12">
      <%= f.label :name, '名前' %>
      <%= f.text_field :name, autocomplete: true %>
    </div>
    <div class="input-field col s12">
      <%= f.label :email, 'メールアドレス' %>
      <%= f.text_field :email, autocomplete: true %>
    </div>
    <div class="input-field col s12">
      <%= f.label :message, '内容' %>
      <%= f.text_area :message, autocomplete: true, class: "materialize-textarea" %>
    </div>
    <%= f.submit '確認', class: 'waves-effect waves-light btn white-text' %>
  <% end %>
</div>

app/views/inquiry/classified_thanks.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
      <p>
        お問い合わせいただきありがとうございました。
      </p>
    </div>
  </div>
</div>

app/views/inquiry/confirm.html.erb
<div class="jumbotron back-jumbo">
<div class="page-header">
  <h2>確認画面</h2>
</div>
 
<%= form_for @inquiry, :url => classified_inquiry_thanks_path(@classified) do |f| %>
  <table class="table">
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :name %>
        <%= @inquiry.name %>
      </td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @inquiry.email %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@inquiry.message) %>
      </td>
    </tr>
  </table>
  <%= f.submit '送信', :class => 'waves-effect waves-light btn white-text' %>
<% end %>
</div>

app/views/inquiry/index.html.erb
<h2>お問い合わせフォーム</h2>
<%= form_for @inquiry, :url => inquiry_confirm_path do |f| %>
<% if @inquiry.errors.any? %>
  <div class="error">
    <strong>入力内容にエラーがあります</strong>
    <ul>
      <% @inquiry.errors.each do |attr, msg| %>
        <li>
          <script type="text/javascript">
          M.toast({html: '<%= msg %>', classes: 'rounded #0288d1 light-blue darken-2'})
          </script>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="input-field col s12">
    <%= f.label :name, '名前' %>
    <%= f.text_field :name, autocomplete: true %>
  </div>
  <div class="input-field col s12">
    <%= f.label :email, 'メールアドレス' %>
    <%= f.text_field :email, autocomplete: true %>
  </div>
  <div class="input-field col s12">
    <%= f.label :message, '内容' %>
    <%= f.text_area :message, autocomplete: true, class: "materialize-textarea" %>
  </div>
  <%= f.submit '確認', class: 'waves-effect waves-light btn white-text' %>
<% end %>

app/views/inquiry/thanks.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 text-center">
      <p>
        お問い合わせいただきありがとうございました。
      </p>
    </div>
  </div>
</div>