config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users do
    get :admin, on: :collection
  end
  
  resources :classifieds do
    get 'inquiry', to: 'inquiry#classified_index'
    post 'inquiry/confirm', to: 'inquiry#classified_confirm'
    post 'inquiry/thanks', to: 'inquiry#classified_thanks'
  end
  resources :areas, only: [:show, :index]
  resources :categories, only: [:show, :index]
  resources :items, only: [:show]
  
  get 'inquiry', to: 'inquiry#index'
  post 'inquiry/confirm', to: 'inquiry#confirm'
  post 'inquiry/thanks', to: 'inquiry#thanks'
  
  get 'policy', to: 'classifieds#policy'
  get 'term', to: 'classifieds#term'
  get 'sitemap', to: redirect('https://s3-ap-northeast-1.amazonaws.com/calgary-board/sitemaps/sitemap.xml.gz')

end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error">
    <ul>
    <% model.errors.full_messages.each do |message| %>
      <li>
        <script type="text/javascript">
        M.toast({html: '<%= message %>', classes: 'rounded #0288d1 light-blue darken-2'})
        </script>
      </li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |message_type, message| %>
      M.toast({html: '<%= message %>',classes: 'rounded <%= message_type %>'})
    <% end %>
  </script>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="page-footer red darken-4">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Cloud Calgary</h5>
        <p class="grey-text text-lighten-4">カルガリー在住の日本人のための掲示板</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">サイトマップ</h5>
        <ul>
          <li>
            <% if logged_in? %>
              <%= link_to 'ログイン', login_path, class: "grey-text text-lighten-3" %>
            <% else %>
              <%= link_to '会員登録', signup_path, class: "grey-text text-lighten-3" %>
            <% end %>
          </li>
          <li><%= link_to 'クラシファイド', classifieds_path, class: "grey-text text-lighten-3" %></li>
          <li><%= link_to '利用規約', term_path, class: "grey-text text-lighten-3" %></li>
          <li><%= link_to 'プライバシーポリシー', policy_path, class: "grey-text text-lighten-3" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2019 Copyright <a href="https://www.cloud-calgary.com" class="grey-text text-lighten-4">cloud-calgary.com</a>
    <a class="grey-text text-lighten-4 right" href="https://katsuhisa-hata.com">created by Katsuhisa-hata.com</a>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<% if logged_in? %>
<ul id="dropdown1" class="dropdown-content red darken-1">
  <li><a href="http://cloud-calgary.com/">Home</a></li>
  <% if current_user.admin_flag? %>
    <li><%= link_to 'Admin', admin_users_path, class: "grey-text text-lighten-3" %></li>
  <% else %>
    <li><%= link_to 'プロフィール', user_path(current_user), class: "grey-text text-lighten-3" %></li>
  <% end %>
  <li><%= link_to 'ログアウト', logout_path, method: :delete, class: "grey-text text-lighten-3" %></li>
</ul>
<% end %>
<nav>
  <div class="nav-wrapper red grey-text text-lighten-3">
    <a href="https://www.cloud-calgary.com/" class="brand-logo">Cloud Calgary</a>
    <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    <ul class="right hide-on-med-and-down">
      <li><a href="https://www.cloud-calgary.com/">Home</a></li>
      <% if logged_in? %>
        <li><a class="dropdown-trigger" href="#!" data-target="dropdown1"><%= current_user.name %><i class="material-icons right">arrow_drop_down</i></a></li>
      <% else %>
        <li><%= link_to '登録', signup_path %></li>
        <li><%= link_to 'ログイン', login_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

<ul class="sidenav" id="mobile-demo">
  <% if logged_in? %>
    <li>
      <ul class="collapsible">
        <li>
          <div class="collapsible-header"><%= current_user.name %><i class="material-icons">arrow_drop_down</i></div>
          <div class="collapsible-body">
            <ul>
              <li><a href="https://www.cloud-calgary.com/">Home</a></li>
              <% if current_user.admin_flag? %>
                <li><%= link_to 'Admin', admin_users_path %></li>
              <% else %>
                <li><%= link_to 'プロフィール', user_path(current_user) %></li>
              <% end %>
              <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            </ul>
          </div>
        </li>
      </ul>
    </li>
  <% else %>
    <li><%= link_to '登録', signup_path %></li>
    <li><%= link_to 'ログイン', login_path %></li>
  <% end %>
  <li>
    <ul class="collapsible">
      <li>
        <div class="collapsible-header"><i class="material-icons">place</i>エリア</div>
        <div class="collapsible-body">
          <span>
            <ul>
              <li><%= link_to "全て", areas_path %></li>
              <li><%= link_to "ダウンタウン", area_path(id: 1) %></li>
              <li><%= link_to "NE", area_path(id: 2) %></li>
              <li><%= link_to "NW", area_path(id: 3) %></li>
              <li><%= link_to "SE", area_path(id: 4) %></li>
              <li><%= link_to "SW", area_path(id: 5) %></li>
            </ul>
          </span>
        </div>
      </li>
      <li>
        <div class="collapsible-header"><i class="material-icons">shopping_cart</i>カテゴリー</div>
        <div class="collapsible-body">
          <span>
            <ul>
              <li><%= link_to "全て", categories_path %></li>
          <li><%= link_to "売ります・買います", category_path(id: 1) %></li>
          <li><%= link_to "部屋", category_path(id: 2) %></li>
          <li><%= link_to "求人", category_path(id: 3) %></li>
          <li><%= link_to "コニュニティー", category_path(id: 4) %></li>
          <li><%= link_to "探す", category_path(id: 5) %></li>
            </ul>
          </span>
        </div>
      </li>
    </ul>
  </li>
</ul>

app/views/layouts/_sidebar.html.erb
<ul class="collapsible">
  <li>
    <div class="collapsible-header"><i class="material-icons">place</i>エリア</div>
    <div class="collapsible-body">
      <span>
        <ul>
          <li><%= link_to "全て", areas_path %></li>
          <li><%= link_to "ダウンタウン", area_path(id: 1) %></li>
          <li><%= link_to "NE", area_path(id: 2) %></li>
          <li><%= link_to "NW", area_path(id: 3) %></li>
          <li><%= link_to "SE", area_path(id: 4) %></li>
          <li><%= link_to "SW", area_path(id: 5) %></li>
        </ul>
      </span>
    </div>
  </li>
  <li>
    <div class="collapsible-header"><i class="material-icons">developer_board</i>カテゴリー</div>
    <div class="collapsible-body">
      <span>
        <ul>
          <li><%= link_to "全て", categories_path %></li>
          <li><%= link_to "売ります・買います", category_path(id: 1) %></li>
          <li><%= link_to "部屋", category_path(id: 2) %></li>
          <li><%= link_to "求人", category_path(id: 3) %></li>
          <li><%= link_to "コニュニティー", category_path(id: 4) %></li>
          <li><%= link_to "探す", category_path(id: 5) %></li>
          
        </ul>
      </span>
    </div>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>クラウドカルガリー</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= analytics_init if Rails.env.production? %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <main>
      <div class="container">
        <div class="row">
          <%= breadcrumbs %>
          <%= render 'layouts/flash_messages' %>
          <%= yield %>
        </div>
      </div>
    </main>
    <%= render 'layouts/footer' %>
    
  </body>
</html>